name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Skip Ruby and bundler setup if you don’t need them for static files
    # - name: Set up Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: '3.2.4'

    # Remove this if you're not using bundler
    # - name: Install dependencies
    #   run: bundle install

    - name: Build project
      run: echo "Building static files..." # Replace this with your actual build command for static files

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build